### ISSUE TITLE
.docx files generated by ZipWriter don't work in WordPad

### ISSUE THREAD

**Issue by charonn0** [charonn0/RB-zlib#16]
Expected behavior: a zip file which was created with the ZipWriter class, and which conforms to the .docx format, should be readable by any application which understands the .docx format.

Actual behavior: Such a zip file fails to open in Microsoft Wordpad. LibreOffice Reader opens it fine, as does Microsoft Word.

**Comment by charonn0** [comment]
This is potentially the result of WordPad expecting the extended data field<sup>1</sup> to store an "extended timestamp"<sup>2</sup>. The ZipWriter class supports writing the extended data field but the user must supply the actual data. Access to the `flag` field in the zip entry header may also be needed, but is not currently provided by the ZipWriter class.

1: [Appnote.txt](https://pkware.cachefly.net/webdocs/casestudies/APPNOTE.TXT): section 4.5 “Extensible data fields”
2: _ibid_: section 4.6 “Third party mappings”

**Comment by XojoGermany** [comment]
I ran into the same issue. Did you found a workaround?

**Comment by charonn0** [comment]
I haven't had the time lately to take a closer look.

**Comment by charonn0** [comment]
Literally 1 character changed.
