### ISSUE TITLE
How to read the content of an entry as a String in memory without extracting the Zip file?

### ISSUE THREAD

**Issue by XojoGermany** [charonn0/RB-zlib#17]
The following code returns an array of Strings to show us the filenames of all entries within a zip folder without the need of physically extract the zip file to the disk (in-memory). This is very handy.
```vb
Dim zip As New PKZip.ZipReader(FolderItem.ShowOpenFileDialog(""))
Dim ret() As String

Do Until zip.LastError <> 0

  ret.Add(zip.CurrentName)

Loop Until Not zip.MoveNext(Nil)

zip.Close
```
What I'm looking for is, to get the String value of each zip entry. Something like `ZipReader.CurrentContent As String` which returns the raw String of entry (textfile, picture etc.).

**Comment by charonn0** [comment]
You can extract the file data to memory by constructing a BinaryStream from a MemoryBlock and then passing the BinaryStream as the parameter to the [MoveNext()](https://github.com/charonn0/RB-zlib/wiki/PKZip.ZipReader.MoveNext) method.

```xojo
Dim data As New MemoryBlock(0)
Dim stream As New BinaryStream(data) 
If zip.MoveNext(stream) = True Then
   MsgBox("OK")
End If
stream.Close()
' the memoryblock now contains the extracted file data
```

Something like a `ZipReader.CurrentContent As String` property would be a significant design change that would face performance problems, particularly when dealing with very large files.

**Comment by XojoGermany** [comment]
Wonderful Andrew, thanks. Since your code snippet isn't exactly integrated into my code snippet, how does it exactly needs to look like?
The following code returns the wrong dictionary pairs. I mean, the CurrentName (Key) doesn't hold the right content. Where am I wrong?
```vb
Dim zip As New PKZip.ZipReader(FolderItem.ShowOpenFileDialog(""))
Dim data As MemoryBlock
Dim stream As BinaryStream
Dim content As String
Var dictContent As New Dictionary

Do Until zip.LastError <> 0
  
  data = New MemoryBlock(0)
  stream = New BinaryStream(data) 
  
  If zip.MoveNext(stream) Then
    
    content = data
    dictContent.Value(zip.CurrentName) = content.DefineEncoding(Encodings.UTF8)
    
  End If
  
  stream.Close
  
Loop Until Not zip.MoveNext(Nil)

zip.Close
```

**Comment by charonn0** [comment]
You need to capture the name (and any other metadata) _before_ calling MoveNext(). You should also call `stream.Close` before accessing the data, and change `Loop Until Not zip.MoveNext(Nil)` to just `Loop`.

```xojo
  Do Until zip.LastError <> 0
    data = New MemoryBlock(0)
    stream = New BinaryStream(data)
    
    Dim name As String = zip.CurrentName ' save the name
    
    Call zip.MoveNext(stream) ' extract into stream
    ' zip.CurrentName now refers to the next item    
    stream.Close  ' close the stream before accessing the data
    
    content = data
    dictContent.Value(name) = content.DefineEncoding(Encodings.UTF8)
  Loop
```

**Comment by XojoGermany** [comment]
Thank you Andrew, this works exactly the way I need it. Great. 🆒
