### ISSUE TITLE
RB-zlib Xojo Question

### ISSUE THREAD

**Issue by neu1886** [charonn0/RB-zlib#9]
Hi Andrew,

I'd like to create a Zip File from Memory. Say I have the following structure I wanna zip:

Root
+ index.html
+ images/
++ picture.png

How can I write/create Zip items directly from String like Chilkat Zip Plugin does ([https://www.example-code.com/excel/zip_api_concepts.asp](https://www.example-code.com/excel/zip_api_concepts.asp)):

zip.AppendString2("HelloWorld2.txt","hello world!","utf-8")

This directly writes a String as a Textfile to the Zip Structure. Any analoge methods in your Library?

Thanks.

**Comment by charonn0** [comment]
I actually just merged [a major update](https://github.com/charonn0/RB-zlib/pull/8) today that changes/extends how zips are handled, so make sure you have the latest version. 

With the update, this library can read zip entry data from a FolderItem, a MemoryBlock, or from anything else that can be used to construct a [Readable](http://docs.xojo.com/index.php/Readable) object.

For example:
```vbnet
  Dim filedata As String = "Hello, world!"
  Dim filestream As New BinaryStream(filedata) ' BinaryStream implements Readable
  
  Dim writer As New PKZip.ZipWriter
  writer.AppendEntry("HelloWord2.txt", filestream, filestream.Length)
  writer.Commit(SpecialFolder.Desktop.Child("test.zip"))
```

Wiki reference:
* [ZipWriter.AppendEntry](https://github.com/charonn0/RB-zlib/wiki/PKZip.ZipWriter.AppendEntry)

**Comment by neu1886** [comment]
Thanks for your reply. Pretty nice and easy to understand. I dropped the Module into my project. I uses the latest Xojo 2018 Release 3 and my app compiles in 64-Bit. I'll get only one Compiler Error (32-Bit Mode works without errors):

> lib.TapeArchive.GetCheckSum, line 7 - Type mismatch error. Expected UInt32, but got Int64
> chksum = chksum + UInt32(32 * 8) ' 8 spaces

How can I fix it, to make your nice library also work in 64-Bit Apps?

**Comment by neu1886** [comment]
OK, i have troubles with my planned In-Memory Zip Container. I will write the following structure into a Zip-File using AppendEntry. It works fine for single files, but not, with folders inside.

Root
+ [Content_Types].xml
+ _rels
  + .rels
+ docProps
  + app.xml
  + core.xml
+ word
  + _rels
    + document.xml.rels
  + theme
    + theme1.xml
  + document.xml
  + fontTable.xml
  + settings.xml
  + styles.xml
  + webSettings.xml
